[package]
name = "rust-utils"
version = "0.1.0"
authors = ["frankeg <garrit.franke@ckc.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rat"
path = "src/cat.rs"